services:
  - type: web
    name: revi-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rev:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
